### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mads256h** [TAPAAL/tapaal-gui#114]
What is the license if any?

**Comment by yrke** [comment]
Hi you can find details about the license af https://www.tapaal.net/download/ see section license: 

- The GUI tool is licensed under the [Open Source Licence 3.0](http://www.opensource.org/licenses/osl-3.0.php)
- The reduction lib, used for automatic translation of TAPN models into UPPAAL Timed Automata and the discrete verification engine verifydtapn are licensed under the [BSD License](http://www.opensource.org/licenses/bsd-license.php).

Open Source Licence 3.0 comes from PIPE2, they have since relicensed using MIT, so we hope to relicense the entire GUI under MIT license. But I haven't been able to go through all the contributions yet to do this.
